## Exercise - DL Tutorial 1 

Please complete the following notebook and upload the completed version to digicampus

## student name: 

For the following 10*10 array (A): 

In [1]:
import numpy as np 
A = np.array([[0.69145505, 0.86931882, 0.88576413, 0.82707554, 0.94754421, 0.54767962,  0.51818679, 0.27907936, 0.95212406, 0.22750068], \
              [0.345638,   0.16172159, 0.87807572, 0.38444467, 0.84255332, 0.69666159,  0.43339905, 0.91927538, 0.58666126, 0.83215206], \
              [0.91359442, 0.06356911, 0.37205853, 0.18242315, 0.37961342, 0.93335263,  0.34068447, 0.48598708, 0.24260729, 0.70004846], \
              [0.75245372, 0.64147803, 0.84013461, 0.6152693,  0.02235612, 0.4492574,  0.55206705, 0.69409179, 0.1666939,  0.67387225], \
              [0.30664677, 0.87559232, 0.07164895, 0.85516997, 0.77945438, 0.51948711,  0.18721151, 0.7690967 , 0.53605078, 0.55431431], \
              [0.1750064,  0.95009262, 0.57121048, 0.87359026, 0.05715099, 0.43202169,  0.3648696,  0.24367817, 0.06807447, 0.46999578], \
              [0.41121198, 0.10125657, 0.0869751,  0.91816382, 0.01738795, 0.19420588,  0.00127754, 0.19281699, 0.56083174, 0.55424236], \
              [0.34467108, 0.18352578, 0.69203741, 0.48087863, 0.39596428, 0.28107969,  0.09727506, 0.11236618, 0.82687268, 0.22700161], \
              [0.92788092, 0.87184167, 0.72492497, 0.94086364, 0.86998108, 0.35178978,  0.45463869, 0.0242793,  0.75607483, 0.21317889], \
              [0.15680697, 0.13109825, 0.93463861, 0.78143659, 0.30680001, 0.67935342,  0.3583568,  0.7522564,  0.19810852, 0.22378965]])
w = np.array([[0.49039597, 0.73424538, 0.08249155, 0.0488797,  0.62525918, 0.29331343, 0.76435348, 0.68825002, 0.53465669, 0.3399619]])

Answer the following 10 questions using Numpy

1.   what is the row index in A that has the largest last element? 


In [2]:
print(np.argmax(A[:,-1]))


1


2.   what is the row index in A that has the second largest last element?

In [3]:
print(np.argsort(A[:,-1])[-2])

2


3.   what are the row indices in A that has a row sum greater than 5?


In [4]:
print(np.where(np.sum(A, axis=1) > 5))

(array([0, 1, 3, 4, 8]),)


4.   What is the sum of all elements of the form A[i, i+1] in A?

In [5]:
print(np.trace(A, offset=1))

a_mask_with_zeros = np.zeros(A.shape)
for i in range(10-1):
    a_mask_with_zeros[i, i+1] = A[i, i+1]
# print a_mask_with_zeros
print(a_mask_with_zeros.sum())

4.06939908
4.06939908


5.   multiply elementwise every row in matrix A by the vector w, and then sum the results for every row


In [6]:
w = [0.49039597, 0.73424538, 0.08249155, 0.0488797,  0.62525918, 0.29331343, 0.76435348, 0.68825002, 0.53465669, 0.3399619]

aw = np.multiply(A, w)
print(np.sum(aw, axis=1))



[3.01853317 2.67114631 2.00801385 2.30303029 2.62819786 1.67847435
 1.01784983 1.38534892 2.68904048 1.65319672]


6.   do the above task in 5. using matrix multiplication


In [7]:
print(np.dot(A, w))

[3.01853317 2.67114631 2.00801385 2.30303029 2.62819786 1.67847435
 1.01784983 1.38534892 2.68904048 1.65319672]


7.   set all elements of A that are larger than 0.5 to 0. What is the sum of the resulting matrix?

In [8]:
a_cut = np.array(A)
a_cut[a_cut > 0.5] = 0
print(a_cut.sum())

print(np.sum([i for i in A.reshape(-1,) if i < 0.5]))

print(np.sum(A[np.where (A < 0.5)]))

12.46007933
12.460079330000001
12.460079330000001


8.   subtract 1 from all elements of A that are smaller than 0.5. What is the sum of the resulting matrix?

In [9]:
a_sub = np.array(A)
a_sub[a_sub < 0.5] -= 1
print(a_sub.sum())

print(np.sum([i-1 if i < 0.5 else i for i in A.reshape(-1)]))

print(np.sum(np.where(A < 0.5, A-1, A)))

-1.15357179
-1.15357179
-1.15357179


9.   what is the sum of all element in A, that are smaller than their column's mean?

In [10]:
a_sma = np.array(A)
# print a_sma
a_sma_mean_col = np.mean(a_sma, axis=0)
# print a_sma_mean_col
a_sma[A - a_sma_mean_col > 0] = 0
print(a_sma.sum())

print(np.sum(np.where(A < A.mean(0), A, 0)))


10.738627639999999
10.738627639999999


10.  create a diagonal matrix B of size 10*10, with B_i,i = i

In [11]:
print(np.diag(range(10)))

b = np.zeros((10,10), dtype=int)
for i in range(10):
    b[i,i] = i
print(b)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
